# .streamlit/secrets.toml

# YouTube API Key
YOUTUBE_API_KEY = "AIzaSyCvuvCBeZK4ecI7vJjOMOFOtxCtGgYXrL8"

# Database Credentials (MySQL Example)
DB_HOST = "localhost"
DB_USER = "root"
DB_PASSWORD = "admin"
DB_NAME = "youtube_data"

# PostgreSQL Example (uncomment if using PostgreSQL)
# PG_DB_HOST = "localhost"
# PG_DB_USER = "your_pg_user"
# PG_DB_PASSWORD = "your_pg_password"
# PG_DB_NAME = "youtube_data"